# Generated by Django 2.2.14 on 2020-07-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colsapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="collection",),
        migrations.AddField(
            model_name="movie",
            name="collections",
            field=models.ManyToManyField(
                related_name="movies", to="colsapp.MovieCollection"
            ),
        ),
    ]
